@extends('layouts.master')

@section('title', 'ChapsChat')

@section('body-class', 'loginMain')

@section('content')

<section class="">
  <div class="container">
    <div class="row justify-content-evenly align-items-center" {{-- style="height: 100vh;" --}}>
      <div class="col-md-4 mt-1">
        <div class="card circleAuth cardLogin">
          <div class="card-body">
            <!-- Session Status -->
            @if (session('status'))
              <div class="alert alert-success mb-4" role="alert">
                {{ session('status') }}
              </div>
            @endif
    
            <form method="POST" action="{{ route('login') }}">
              @csrf
    
              <!-- Email Address -->
              <label class="form-label loginLabel" for="email">{{ __('Email') }}</label>
              <div class="input-group mb-3">
                <span class="input-group-text login" for="email"><i class="fa-solid fa-solid fa-at iconAuth" data-bs-custom-class="custom-tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="Enter your e-mail address">{{ __('') }}</i></span>
                <input id="email" class="form-control login" title="Enter your e-mail address" type="email" name="email" value="{{ old('email') }}" required autofocus autocomplete="username">
                @error('email')
                  <div class="text-danger mt-2">{{ $message }}</div>
                @enderror
              </div>
              
              <!-- Password -->
              <label class="form-label loginLabel" for="password">{{ __('Password') }}</label>
              <div class="input-group mb-3">  
                <span class="input-group-text login" for="email"><i class="fa-solid fa-key iconAuth" data-bs-custom-class="custom-tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="Enter your password">{{ __('') }}</i></span>
                <input id="password" class="form-control login" title="Enter your password" type="password" name="password" required autocomplete="current-password">
                @error('password')
                  <div class="text-danger mt-2">{{ $message }}</div>
                @enderror
              </div>
    
              <!-- Remember Me -->
              <div class="mb-3 form-check">
                <input id="remember_me" type="checkbox" class="form-check-input" name="remember">
                <label class="form-check-label loginLabel" for="remember_me">{{ __('Remember me') }}</label>
              </div>
    
              <!-- Forgot your password? -->
              <div class="d-md-flex justify-content-md-between align-items-md-center flex-md-column text-center">
                @if (Route::has('password.request'))
                  <a class="loginLabel text-decoration-none mb-3" href="{{ route('password.request') }}">{{ __('Forgot your password?') }}</a>
                @endif
                <button type="submit" class="btn btn-circle ml-md-4">{{ __('Log in') }}</button>
              </div>
              
            </form>
          </div>
        </div>
      </div>


<!-- QUOTE TYPEWRITER LOGIN -->

      <div  class="col-sm-6 p-3">
        <button id="playButton">Play Audio</button>
        <div class="typewriter-wrapper" id="colElement" style="display: none;">
          <blockquote class="blockquote-fluid mb-0 p-4">
            <span id="contentSpan" class="type" style="--n:590">"Playing, testing, and trying are not mere frivolous endeavors, but essential elements that unlock the true potential of humanity. Through play, we discover the limits of our imagination and creativity, paving the way for innovation. Testing allows us to push boundaries, uncover flaws, and refine our ideas, ensuring progress and growth. Trying, with its inherent risk and uncertainty, is the catalyst for personal development and the gateway to remarkable achievements. Embrace these pursuits, for they hold the power to transform the world and unveil the extraordinary within ourselves."</span>
            <footer class="blockquote-footer mt-2">Quote generated by <cite title="Source title">ChatGPT, 29/05/2023 <br>(asked for giving a quote about the importance for individual humans of playing, testing, and trying).</cite></footer>
          </blockquote>
        </div>
      </div>
      

    </div>
  </div>


</section>

<audio id="myAudioLog">
  <source src="./assets/audio/typewriter-1.mp3" type="audio/mpeg">
  Your browser does not support the audio element.
</audio>
<script>
document.addEventListener("DOMContentLoaded", function() {
var audio = document.getElementById("myAudioLog");
var playButton = document.getElementById("playButton");
var colElement = document.getElementById("colElement");

// Play audio and show the colElement when the button is clicked
playButton.addEventListener("click", function() {
  audio.play();
  colElement.classList.add("show");
});
});

</script>

  
@endsection
