@extends('layouts.master')

@section('title', 'ChapsChat')

@section('body-class', 'loginMain')

@section('content')

<section class="">
  <div class="container">
    <div class="row justify-content-evenly align-items-center" {{-- style="height: 100vh;" --}}>
      <div class="col-md-5 mt-1 animate__animated animate__flipInX">
        <div class="card circleAuth cardLogin">
          <div class="card-body">
            <!-- Session Status -->
            @if (session('status'))
              <div class="alert alert-success mb-4" role="alert">
                {{ session('status') }}
              </div>
            @endif
    
            <form method="POST" action="{{ route('login') }}">
              @csrf
    
              <!-- Email Address -->
              <label class="form-label loginLabel" for="email">{{ __('Email') }}</label>
              <div class="input-group mb-3">
                <span class="input-group-text login labelAuth" for="email"><i class="fa-solid fa-solid fa-at iconAuth" data-bs-custom-class="custom-tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="Enter your e-mail address">{{ __('') }}</i></span>
                <input id="email" class="form-control login" title="Enter your e-mail address" type="email" name="email" value="{{ old('email') }}" required autofocus autocomplete="username">
                @error('email')
                  <div class="text-danger mt-2">{{ $message }}</div>
                @enderror
              </div>
              
              <!-- Password -->
              <label class="form-label loginLabel" for="password">{{ __('Password') }}</label>
              <div class="input-group mb-3">  
                <span class="input-group-text login labelAuth" for="email"><i class="fa-solid fa-key iconAuth" data-bs-custom-class="custom-tooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="Enter your password">{{ __('') }}</i></span>
                <input id="password" class="form-control login" title="Enter your password" type="password" name="password" required autocomplete="current-password">
                @error('password')
                  <div class="text-danger mt-2">{{ $message }}</div>
                @enderror
              </div>
    
              <!-- Remember Me -->
              <div class="mb-3 form-check">
                <input id="remember_me" type="checkbox" class="form-check-input" name="remember">
                <label class="form-check-label loginLabel" for="remember_me">{{ __('Remember me') }}</label>
              </div>
    
              <!-- Forgot your password? -->
              <div class="d-md-flex justify-content-md-between align-items-md-center flex-md-column text-center">
                @if (Route::has('password.request'))
                  <a class="loginLabel text-decoration-none mb-3" href="{{ route('password.request') }}">{{ __('Forgot your password?') }}</a>
                @endif
                <button type="submit" class="btn btn-lg btn-auth p-2 ml-md-4"><span class="material-symbols-outlined pe-3" style="padding-left:-2rem;">
                  login
                  </span>{{-- {{ __('Log in') }} --}}</button>
              </div>
              
            </form>
          </div>
        </div>
      </div>

<!-- QUOTE TYPEWRITER LOGIN -->

      <div  class="col-sm-6 p-3 animate__animated animate__flipInY">
        <a class="col-6 btn btn-circleType" id="playButtonLog" href="#" style="display: inline-block; padding: 5px;">
          <img class="col-12 image-fluid" src="./assets/img/typewriter.png" alt="typewriter_cute">
        </a>
        {{-- <button class="btn btn-own" id="playButtonLog"><span class="material-symbols-outlined">play_circle</span>Play Audio</button> --}}
        <div class="typewriter-wrapper" id="colElementLog" style="display: none;">
          <blockquote class="blockquote-fluid mb-0 p-4">
            <span id="contentSpan" class="type" style="--n:590">"Playing, testing, and trying are not mere frivolous endeavors, but essential elements that unlock the true potential of humanity. Through play, we discover the limits of our imagination and creativity, paving the way for innovation. Testing allows us to push boundaries, uncover flaws, and refine our ideas, ensuring progress and growth. Trying, with its inherent risk and uncertainty, is the catalyst for personal development and the gateway to remarkable achievements. Embrace these pursuits, for they hold the power to transform the world and unveil the extraordinary within ourselves."</span>
            <footer class="blockquote-footer mt-2">Quote generated by <cite title="Source title">ChatGPT, 29/05/2023 <br>(asked for giving a quote about the importance for individual humans of playing, testing, and trying).</cite></footer>
          </blockquote>
        </div>
      </div>
    </div>
  </div>

</section>

<audio id="myAudioReg">
  <source src="./assets/audio/typewriter-1.mp3" type="audio/mpeg">
  Your browser does not support the audio element.
</audio>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var audio = document.getElementById("myAudioReg");
    var playButton = document.getElementById("playButtonLog");
    var colElement = document.getElementById("colElementLog");
    var playCount = 3.5; // Desired play count (e.g., 3.5 seconds)
    var isPlaying = false; // Flag to track audio playing state

    function playAudio() {
      audio.currentTime = 0; // Reset current time
      audio.play();
      colElement.classList.add("show");
      isPlaying = true;
    }

    function handleAudioEnd() {
      playCount -= 1; // Decrease play count by 1 second
      if (playCount > 0) {
        playAudio();
      } else {
        audio.pause();
        audio.currentTime = 0;
        isPlaying = false;
      }
    }

    // Play audio and show the colElement when the button is clicked
    playButton.addEventListener("click", function() {
      if (!isPlaying) {
        playAudio();
      }
    });

    // Event listener to handle audio pause and end
    audio.addEventListener('pause', function() {
      if (isPlaying) {
        handleAudioEnd();
      }
    });

    audio.addEventListener('ended', function() {
      if (isPlaying) {
        handleAudioEnd();
      }
    });
  });
</script>

@endsection
